name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Install TeX Live
      run: bash .github/workflows/install-texlive.sh

    - name: Test bst
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        make testbst

    - name: Test citation styles
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        l3build check

    - name: Test doc
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        make doc
